/*
 * This file was generated automatically by ExtUtils::ParseXS version 3.51 from the
 * contents of Builtins.xs. Do not edit this file, edit Builtins.xs instead.
 *
 *    ANY CHANGES MADE HERE WILL BE LOST!
 *
 */

#line 1 "lib/GCC/Builtins.xs"

/*
 #######################################################
 # Warning: this file has been auto-generated
 # DO NOT EDIT if you can resist it.
 # neither edit typemap not GCC/Buildins.pm
 # make your edits in sbin/build-gcc-builtins-package.pl
 #######################################################
*/
#define PERL_NO_GET_CONTEXT // we'll define thread context if necessary (faster)
#include "EXTERN.h"         // globals/constant import locations
#include "perl.h"           // Perl symbols, structures and constants definition
#include "XSUB.h"           // xsubpp functions and macros
#include <stdlib.h>         // rand()

#ifndef __has_builtin
#error "Your compiler does not support builtin functions, note this is a naive and lame test."
#endif

typedef __int128 int128_t;
typedef unsigned __int128 uint128_t;

#line 33 "lib/GCC/Builtins.c"
#ifndef PERL_UNUSED_VAR
#  define PERL_UNUSED_VAR(var) if (0) var = var
#endif

#ifndef dVAR
#  define dVAR		dNOOP
#endif


/* This stuff is not part of the API! You have been warned. */
#ifndef PERL_VERSION_DECIMAL
#  define PERL_VERSION_DECIMAL(r,v,s) (r*1000000 + v*1000 + s)
#endif
#ifndef PERL_DECIMAL_VERSION
#  define PERL_DECIMAL_VERSION \
	  PERL_VERSION_DECIMAL(PERL_REVISION,PERL_VERSION,PERL_SUBVERSION)
#endif
#ifndef PERL_VERSION_GE
#  define PERL_VERSION_GE(r,v,s) \
	  (PERL_DECIMAL_VERSION >= PERL_VERSION_DECIMAL(r,v,s))
#endif
#ifndef PERL_VERSION_LE
#  define PERL_VERSION_LE(r,v,s) \
	  (PERL_DECIMAL_VERSION <= PERL_VERSION_DECIMAL(r,v,s))
#endif

/* XS_INTERNAL is the explicit static-linkage variant of the default
 * XS macro.
 *
 * XS_EXTERNAL is the same as XS_INTERNAL except it does not include
 * "STATIC", ie. it exports XSUB symbols. You probably don't want that
 * for anything but the BOOT XSUB.
 *
 * See XSUB.h in core!
 */


/* TODO: This might be compatible further back than 5.10.0. */
#if PERL_VERSION_GE(5, 10, 0) && PERL_VERSION_LE(5, 15, 1)
#  undef XS_EXTERNAL
#  undef XS_INTERNAL
#  if defined(__CYGWIN__) && defined(USE_DYNAMIC_LOADING)
#    define XS_EXTERNAL(name) __declspec(dllexport) XSPROTO(name)
#    define XS_INTERNAL(name) STATIC XSPROTO(name)
#  endif
#  if defined(__SYMBIAN32__)
#    define XS_EXTERNAL(name) EXPORT_C XSPROTO(name)
#    define XS_INTERNAL(name) EXPORT_C STATIC XSPROTO(name)
#  endif
#  ifndef XS_EXTERNAL
#    if defined(HASATTRIBUTE_UNUSED) && !defined(__cplusplus)
#      define XS_EXTERNAL(name) void name(pTHX_ CV* cv __attribute__unused__)
#      define XS_INTERNAL(name) STATIC void name(pTHX_ CV* cv __attribute__unused__)
#    else
#      ifdef __cplusplus
#        define XS_EXTERNAL(name) extern "C" XSPROTO(name)
#        define XS_INTERNAL(name) static XSPROTO(name)
#      else
#        define XS_EXTERNAL(name) XSPROTO(name)
#        define XS_INTERNAL(name) STATIC XSPROTO(name)
#      endif
#    endif
#  endif
#endif

/* perl >= 5.10.0 && perl <= 5.15.1 */


/* The XS_EXTERNAL macro is used for functions that must not be static
 * like the boot XSUB of a module. If perl didn't have an XS_EXTERNAL
 * macro defined, the best we can do is assume XS is the same.
 * Dito for XS_INTERNAL.
 */
#ifndef XS_EXTERNAL
#  define XS_EXTERNAL(name) XS(name)
#endif
#ifndef XS_INTERNAL
#  define XS_INTERNAL(name) XS(name)
#endif

/* Now, finally, after all this mess, we want an ExtUtils::ParseXS
 * internal macro that we're free to redefine for varying linkage due
 * to the EXPORT_XSUB_SYMBOLS XS keyword. This is internal, use
 * XS_EXTERNAL(name) or XS_INTERNAL(name) in your code if you need to!
 */

#undef XS_EUPXS
#if defined(PERL_EUPXS_ALWAYS_EXPORT)
#  define XS_EUPXS(name) XS_EXTERNAL(name)
#else
   /* default to internal */
#  define XS_EUPXS(name) XS_INTERNAL(name)
#endif

#ifndef PERL_ARGS_ASSERT_CROAK_XS_USAGE
#define PERL_ARGS_ASSERT_CROAK_XS_USAGE assert(cv); assert(params)

/* prototype to pass -Wmissing-prototypes */
STATIC void
S_croak_xs_usage(const CV *const cv, const char *const params);

STATIC void
S_croak_xs_usage(const CV *const cv, const char *const params)
{
    const GV *const gv = CvGV(cv);

    PERL_ARGS_ASSERT_CROAK_XS_USAGE;

    if (gv) {
        const char *const gvname = GvNAME(gv);
        const HV *const stash = GvSTASH(gv);
        const char *const hvname = stash ? HvNAME(stash) : NULL;

        if (hvname)
	    Perl_croak_nocontext("Usage: %s::%s(%s)", hvname, gvname, params);
        else
	    Perl_croak_nocontext("Usage: %s(%s)", gvname, params);
    } else {
        /* Pants. I don't think that it should be possible to get here. */
	Perl_croak_nocontext("Usage: CODE(0x%" UVxf ")(%s)", PTR2UV(cv), params);
    }
}
#undef  PERL_ARGS_ASSERT_CROAK_XS_USAGE

#define croak_xs_usage        S_croak_xs_usage

#endif

/* NOTE: the prototype of newXSproto() is different in versions of perls,
 * so we define a portable version of newXSproto()
 */
#ifdef newXS_flags
#define newXSproto_portable(name, c_impl, file, proto) newXS_flags(name, c_impl, file, proto, 0)
#else
#define newXSproto_portable(name, c_impl, file, proto) (PL_Sv=(SV*)newXS(name, c_impl, file), sv_setpv(PL_Sv, proto), (CV*)PL_Sv)
#endif /* !defined(newXS_flags) */

#if PERL_VERSION_LE(5, 21, 5)
#  define newXS_deffile(a,b) Perl_newXS(aTHX_ a,b,file)
#else
#  define newXS_deffile(a,b) Perl_newXS_deffile(aTHX_ a,b)
#endif

#line 177 "lib/GCC/Builtins.c"

XS_EUPXS(XS_GCC__Builtins_bswap16); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_GCC__Builtins_bswap16)
{
    dVAR; dXSARGS;
    if (items != 1)
       croak_xs_usage(cv,  "x");
    {
	uint16_t	RETVAL;
	dXSTARG;
	uint16_t	x = (uint16_t)SvUV(ST(0))
;
#line 32 "lib/GCC/Builtins.xs"
    RETVAL = __builtin_bswap16(x);
#line 192 "lib/GCC/Builtins.c"
	XSprePUSH;
	PUSHu((UV)RETVAL);
    }
    XSRETURN(1);
}


XS_EUPXS(XS_GCC__Builtins_bswap32); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_GCC__Builtins_bswap32)
{
    dVAR; dXSARGS;
    if (items != 1)
       croak_xs_usage(cv,  "x");
    {
	uint32_t	RETVAL;
	dXSTARG;
	uint32_t	x = (uint32_t)SvUV(ST(0))
;
#line 40 "lib/GCC/Builtins.xs"
    RETVAL = __builtin_bswap32(x);
#line 213 "lib/GCC/Builtins.c"
	XSprePUSH;
	PUSHu((UV)RETVAL);
    }
    XSRETURN(1);
}


XS_EUPXS(XS_GCC__Builtins_bswap64); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_GCC__Builtins_bswap64)
{
    dVAR; dXSARGS;
    if (items != 1)
       croak_xs_usage(cv,  "x");
    {
	uint64_t	RETVAL;
	dXSTARG;
	uint64_t	x = (uint64_t)SvUV(ST(0))
;
#line 48 "lib/GCC/Builtins.xs"
    RETVAL = __builtin_bswap64(x);
#line 234 "lib/GCC/Builtins.c"
	XSprePUSH;
	PUSHu((UV)RETVAL);
    }
    XSRETURN(1);
}


XS_EUPXS(XS_GCC__Builtins_clrsb); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_GCC__Builtins_clrsb)
{
    dVAR; dXSARGS;
    if (items != 1)
       croak_xs_usage(cv,  "x");
    {
	int	RETVAL;
	dXSTARG;
	int	x = (int)SvIV(ST(0))
;
#line 56 "lib/GCC/Builtins.xs"
    RETVAL = __builtin_clrsb(x);
#line 255 "lib/GCC/Builtins.c"
	XSprePUSH;
	PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}


XS_EUPXS(XS_GCC__Builtins_clrsbl); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_GCC__Builtins_clrsbl)
{
    dVAR; dXSARGS;
    if (items != 1)
       croak_xs_usage(cv,  "aaa");
    {
	int	RETVAL;
	dXSTARG;
	long	aaa = (long)SvIV(ST(0))
;
#line 64 "lib/GCC/Builtins.xs"
    RETVAL = __builtin_clrsbl(aaa);
#line 276 "lib/GCC/Builtins.c"
	XSprePUSH;
	PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}


XS_EUPXS(XS_GCC__Builtins_clrsbll); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_GCC__Builtins_clrsbll)
{
    dVAR; dXSARGS;
    if (items != 1)
       croak_xs_usage(cv,  "aaa");
    {
	int	RETVAL;
	dXSTARG;
	long long	aaa = (long)SvIV(ST(0))
;
#line 72 "lib/GCC/Builtins.xs"
    RETVAL = __builtin_clrsbll(aaa);
#line 297 "lib/GCC/Builtins.c"
	XSprePUSH;
	PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}


XS_EUPXS(XS_GCC__Builtins_clz); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_GCC__Builtins_clz)
{
    dVAR; dXSARGS;
    if (items != 1)
       croak_xs_usage(cv,  "x");
    {
	int	RETVAL;
	dXSTARG;
	unsigned int	x = (unsigned int)SvUV(ST(0))
;
#line 80 "lib/GCC/Builtins.xs"
    RETVAL = __builtin_clz(x);
#line 318 "lib/GCC/Builtins.c"
	XSprePUSH;
	PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}


XS_EUPXS(XS_GCC__Builtins_clzl); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_GCC__Builtins_clzl)
{
    dVAR; dXSARGS;
    if (items != 1)
       croak_xs_usage(cv,  "aaa");
    {
	int	RETVAL;
	dXSTARG;
	unsigned long	aaa = (unsigned long)SvUV(ST(0))
;
#line 88 "lib/GCC/Builtins.xs"
    RETVAL = __builtin_clzl(aaa);
#line 339 "lib/GCC/Builtins.c"
	XSprePUSH;
	PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}


XS_EUPXS(XS_GCC__Builtins_clzll); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_GCC__Builtins_clzll)
{
    dVAR; dXSARGS;
    if (items != 1)
       croak_xs_usage(cv,  "aaa");
    {
	int	RETVAL;
	dXSTARG;
	unsigned long long	aaa = (unsigned long)SvUV(ST(0))
;
#line 96 "lib/GCC/Builtins.xs"
    RETVAL = __builtin_clzll(aaa);
#line 360 "lib/GCC/Builtins.c"
	XSprePUSH;
	PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}


XS_EUPXS(XS_GCC__Builtins_ctz); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_GCC__Builtins_ctz)
{
    dVAR; dXSARGS;
    if (items != 1)
       croak_xs_usage(cv,  "x");
    {
	int	RETVAL;
	dXSTARG;
	unsigned int	x = (unsigned int)SvUV(ST(0))
;
#line 104 "lib/GCC/Builtins.xs"
    RETVAL = __builtin_ctz(x);
#line 381 "lib/GCC/Builtins.c"
	XSprePUSH;
	PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}


XS_EUPXS(XS_GCC__Builtins_ctzl); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_GCC__Builtins_ctzl)
{
    dVAR; dXSARGS;
    if (items != 1)
       croak_xs_usage(cv,  "aaa");
    {
	int	RETVAL;
	dXSTARG;
	unsigned long	aaa = (unsigned long)SvUV(ST(0))
;
#line 112 "lib/GCC/Builtins.xs"
    RETVAL = __builtin_ctzl(aaa);
#line 402 "lib/GCC/Builtins.c"
	XSprePUSH;
	PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}


XS_EUPXS(XS_GCC__Builtins_ctzll); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_GCC__Builtins_ctzll)
{
    dVAR; dXSARGS;
    if (items != 1)
       croak_xs_usage(cv,  "aaa");
    {
	int	RETVAL;
	dXSTARG;
	unsigned long long	aaa = (unsigned long)SvUV(ST(0))
;
#line 120 "lib/GCC/Builtins.xs"
    RETVAL = __builtin_ctzll(aaa);
#line 423 "lib/GCC/Builtins.c"
	XSprePUSH;
	PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}


XS_EUPXS(XS_GCC__Builtins_ffs); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_GCC__Builtins_ffs)
{
    dVAR; dXSARGS;
    if (items != 1)
       croak_xs_usage(cv,  "x");
    {
	int	RETVAL;
	dXSTARG;
	int	x = (int)SvIV(ST(0))
;
#line 128 "lib/GCC/Builtins.xs"
    RETVAL = __builtin_ffs(x);
#line 444 "lib/GCC/Builtins.c"
	XSprePUSH;
	PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}


XS_EUPXS(XS_GCC__Builtins_ffsl); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_GCC__Builtins_ffsl)
{
    dVAR; dXSARGS;
    if (items != 1)
       croak_xs_usage(cv,  "aaa");
    {
	int	RETVAL;
	dXSTARG;
	long	aaa = (long)SvIV(ST(0))
;
#line 136 "lib/GCC/Builtins.xs"
    RETVAL = __builtin_ffsl(aaa);
#line 465 "lib/GCC/Builtins.c"
	XSprePUSH;
	PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}


XS_EUPXS(XS_GCC__Builtins_ffsll); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_GCC__Builtins_ffsll)
{
    dVAR; dXSARGS;
    if (items != 1)
       croak_xs_usage(cv,  "aaa");
    {
	int	RETVAL;
	dXSTARG;
	long long	aaa = (long)SvIV(ST(0))
;
#line 144 "lib/GCC/Builtins.xs"
    RETVAL = __builtin_ffsll(aaa);
#line 486 "lib/GCC/Builtins.c"
	XSprePUSH;
	PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}


XS_EUPXS(XS_GCC__Builtins_huge_val); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_GCC__Builtins_huge_val)
{
    dVAR; dXSARGS;
    if (items != 0)
       croak_xs_usage(cv,  "");
    {
	double	RETVAL;
	dXSTARG;
#line 152 "lib/GCC/Builtins.xs"
    RETVAL = __builtin_huge_val();
#line 505 "lib/GCC/Builtins.c"
	XSprePUSH;
	PUSHn((double)RETVAL);
    }
    XSRETURN(1);
}


XS_EUPXS(XS_GCC__Builtins_huge_valf); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_GCC__Builtins_huge_valf)
{
    dVAR; dXSARGS;
    if (items != 0)
       croak_xs_usage(cv,  "");
    {
	float	RETVAL;
	dXSTARG;
#line 160 "lib/GCC/Builtins.xs"
    RETVAL = __builtin_huge_valf();
#line 524 "lib/GCC/Builtins.c"
	XSprePUSH;
	PUSHn((double)RETVAL);
    }
    XSRETURN(1);
}


XS_EUPXS(XS_GCC__Builtins_huge_vall); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_GCC__Builtins_huge_vall)
{
    dVAR; dXSARGS;
    if (items != 0)
       croak_xs_usage(cv,  "");
    {
	long double	RETVAL;
	dXSTARG;
#line 168 "lib/GCC/Builtins.xs"
    RETVAL = __builtin_huge_vall();
#line 543 "lib/GCC/Builtins.c"
	XSprePUSH;
	PUSHn((double)RETVAL);
    }
    XSRETURN(1);
}


XS_EUPXS(XS_GCC__Builtins_inf); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_GCC__Builtins_inf)
{
    dVAR; dXSARGS;
    if (items != 0)
       croak_xs_usage(cv,  "");
    {
	double	RETVAL;
	dXSTARG;
#line 176 "lib/GCC/Builtins.xs"
    RETVAL = __builtin_inf();
#line 562 "lib/GCC/Builtins.c"
	XSprePUSH;
	PUSHn((double)RETVAL);
    }
    XSRETURN(1);
}


XS_EUPXS(XS_GCC__Builtins_infd128); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_GCC__Builtins_infd128)
{
    dVAR; dXSARGS;
    if (items != 0)
       croak_xs_usage(cv,  "");
    {
	_Decimal128	RETVAL;
	dXSTARG;
#line 184 "lib/GCC/Builtins.xs"
    RETVAL = __builtin_infd128();
#line 581 "lib/GCC/Builtins.c"
	XSprePUSH;
	PUSHn((double)RETVAL);
    }
    XSRETURN(1);
}


XS_EUPXS(XS_GCC__Builtins_infd32); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_GCC__Builtins_infd32)
{
    dVAR; dXSARGS;
    if (items != 0)
       croak_xs_usage(cv,  "");
    {
	_Decimal32	RETVAL;
	dXSTARG;
#line 192 "lib/GCC/Builtins.xs"
    RETVAL = __builtin_infd32();
#line 600 "lib/GCC/Builtins.c"
	XSprePUSH;
	PUSHn((double)RETVAL);
    }
    XSRETURN(1);
}


XS_EUPXS(XS_GCC__Builtins_infd64); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_GCC__Builtins_infd64)
{
    dVAR; dXSARGS;
    if (items != 0)
       croak_xs_usage(cv,  "");
    {
	_Decimal64	RETVAL;
	dXSTARG;
#line 200 "lib/GCC/Builtins.xs"
    RETVAL = __builtin_infd64();
#line 619 "lib/GCC/Builtins.c"
	XSprePUSH;
	PUSHn((double)RETVAL);
    }
    XSRETURN(1);
}


XS_EUPXS(XS_GCC__Builtins_inff); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_GCC__Builtins_inff)
{
    dVAR; dXSARGS;
    if (items != 0)
       croak_xs_usage(cv,  "");
    {
	float	RETVAL;
	dXSTARG;
#line 208 "lib/GCC/Builtins.xs"
    RETVAL = __builtin_inff();
#line 638 "lib/GCC/Builtins.c"
	XSprePUSH;
	PUSHn((double)RETVAL);
    }
    XSRETURN(1);
}


XS_EUPXS(XS_GCC__Builtins_infl); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_GCC__Builtins_infl)
{
    dVAR; dXSARGS;
    if (items != 0)
       croak_xs_usage(cv,  "");
    {
	long double	RETVAL;
	dXSTARG;
#line 216 "lib/GCC/Builtins.xs"
    RETVAL = __builtin_infl();
#line 657 "lib/GCC/Builtins.c"
	XSprePUSH;
	PUSHn((double)RETVAL);
    }
    XSRETURN(1);
}


XS_EUPXS(XS_GCC__Builtins_nan); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_GCC__Builtins_nan)
{
    dVAR; dXSARGS;
    if (items != 1)
       croak_xs_usage(cv,  "str");
    {
	double	RETVAL;
	dXSTARG;
	const char *	str = (const char *)SvPV_nolen(ST(0))
;
#line 224 "lib/GCC/Builtins.xs"
    RETVAL = __builtin_nan(str);
#line 678 "lib/GCC/Builtins.c"
	XSprePUSH;
	PUSHn((double)RETVAL);
    }
    XSRETURN(1);
}


XS_EUPXS(XS_GCC__Builtins_nanf); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_GCC__Builtins_nanf)
{
    dVAR; dXSARGS;
    if (items != 1)
       croak_xs_usage(cv,  "str");
    {
	float	RETVAL;
	dXSTARG;
	const char *	str = (const char *)SvPV_nolen(ST(0))
;
#line 232 "lib/GCC/Builtins.xs"
    RETVAL = __builtin_nanf(str);
#line 699 "lib/GCC/Builtins.c"
	XSprePUSH;
	PUSHn((double)RETVAL);
    }
    XSRETURN(1);
}


XS_EUPXS(XS_GCC__Builtins_nanl); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_GCC__Builtins_nanl)
{
    dVAR; dXSARGS;
    if (items != 1)
       croak_xs_usage(cv,  "str");
    {
	long double	RETVAL;
	dXSTARG;
	const char *	str = (const char *)SvPV_nolen(ST(0))
;
#line 240 "lib/GCC/Builtins.xs"
    RETVAL = __builtin_nanl(str);
#line 720 "lib/GCC/Builtins.c"
	XSprePUSH;
	PUSHn((double)RETVAL);
    }
    XSRETURN(1);
}


XS_EUPXS(XS_GCC__Builtins_parity); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_GCC__Builtins_parity)
{
    dVAR; dXSARGS;
    if (items != 1)
       croak_xs_usage(cv,  "x");
    {
	int	RETVAL;
	dXSTARG;
	unsigned int	x = (unsigned int)SvUV(ST(0))
;
#line 248 "lib/GCC/Builtins.xs"
    RETVAL = __builtin_parity(x);
#line 741 "lib/GCC/Builtins.c"
	XSprePUSH;
	PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}


XS_EUPXS(XS_GCC__Builtins_parityl); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_GCC__Builtins_parityl)
{
    dVAR; dXSARGS;
    if (items != 1)
       croak_xs_usage(cv,  "aaa");
    {
	int	RETVAL;
	dXSTARG;
	unsigned long	aaa = (unsigned long)SvUV(ST(0))
;
#line 256 "lib/GCC/Builtins.xs"
    RETVAL = __builtin_parityl(aaa);
#line 762 "lib/GCC/Builtins.c"
	XSprePUSH;
	PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}


XS_EUPXS(XS_GCC__Builtins_parityll); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_GCC__Builtins_parityll)
{
    dVAR; dXSARGS;
    if (items != 1)
       croak_xs_usage(cv,  "aaa");
    {
	int	RETVAL;
	dXSTARG;
	unsigned long long	aaa = (unsigned long)SvUV(ST(0))
;
#line 264 "lib/GCC/Builtins.xs"
    RETVAL = __builtin_parityll(aaa);
#line 783 "lib/GCC/Builtins.c"
	XSprePUSH;
	PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}


XS_EUPXS(XS_GCC__Builtins_popcount); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_GCC__Builtins_popcount)
{
    dVAR; dXSARGS;
    if (items != 1)
       croak_xs_usage(cv,  "x");
    {
	int	RETVAL;
	dXSTARG;
	unsigned int	x = (unsigned int)SvUV(ST(0))
;
#line 272 "lib/GCC/Builtins.xs"
    RETVAL = __builtin_popcount(x);
#line 804 "lib/GCC/Builtins.c"
	XSprePUSH;
	PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}


XS_EUPXS(XS_GCC__Builtins_popcountl); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_GCC__Builtins_popcountl)
{
    dVAR; dXSARGS;
    if (items != 1)
       croak_xs_usage(cv,  "aaa");
    {
	int	RETVAL;
	dXSTARG;
	unsigned long	aaa = (unsigned long)SvUV(ST(0))
;
#line 280 "lib/GCC/Builtins.xs"
    RETVAL = __builtin_popcountl(aaa);
#line 825 "lib/GCC/Builtins.c"
	XSprePUSH;
	PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}


XS_EUPXS(XS_GCC__Builtins_popcountll); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_GCC__Builtins_popcountll)
{
    dVAR; dXSARGS;
    if (items != 1)
       croak_xs_usage(cv,  "aaa");
    {
	int	RETVAL;
	dXSTARG;
	unsigned long long	aaa = (unsigned long)SvUV(ST(0))
;
#line 288 "lib/GCC/Builtins.xs"
    RETVAL = __builtin_popcountll(aaa);
#line 846 "lib/GCC/Builtins.c"
	XSprePUSH;
	PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}


XS_EUPXS(XS_GCC__Builtins_powi); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_GCC__Builtins_powi)
{
    dVAR; dXSARGS;
    if (items != 2)
       croak_xs_usage(cv,  "aaa, aab");
    {
	double	RETVAL;
	dXSTARG;
	double	aaa = (double)SvNV(ST(0))
;
	int	aab = (int)SvIV(ST(1))
;
#line 296 "lib/GCC/Builtins.xs"
    RETVAL = __builtin_powi(aaa,aab);
#line 869 "lib/GCC/Builtins.c"
	XSprePUSH;
	PUSHn((double)RETVAL);
    }
    XSRETURN(1);
}


XS_EUPXS(XS_GCC__Builtins_powif); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_GCC__Builtins_powif)
{
    dVAR; dXSARGS;
    if (items != 2)
       croak_xs_usage(cv,  "aaa, aab");
    {
	float	RETVAL;
	dXSTARG;
	float	aaa = (float)SvNV(ST(0))
;
	int	aab = (int)SvIV(ST(1))
;
#line 304 "lib/GCC/Builtins.xs"
    RETVAL = __builtin_powif(aaa,aab);
#line 892 "lib/GCC/Builtins.c"
	XSprePUSH;
	PUSHn((double)RETVAL);
    }
    XSRETURN(1);
}


XS_EUPXS(XS_GCC__Builtins_powil); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_GCC__Builtins_powil)
{
    dVAR; dXSARGS;
    if (items != 2)
       croak_xs_usage(cv,  "aaa, aab");
    {
	long double	RETVAL;
	dXSTARG;
	long double	aaa = (double)SvNV(ST(0))
;
	int	aab = (int)SvIV(ST(1))
;
#line 312 "lib/GCC/Builtins.xs"
    RETVAL = __builtin_powil(aaa,aab);
#line 915 "lib/GCC/Builtins.c"
	XSprePUSH;
	PUSHn((double)RETVAL);
    }
    XSRETURN(1);
}

#ifdef __cplusplus
extern "C" {
#endif
XS_EXTERNAL(boot_GCC__Builtins); /* prototype to pass -Wmissing-prototypes */
XS_EXTERNAL(boot_GCC__Builtins)
{
#if PERL_VERSION_LE(5, 21, 5)
    dVAR; dXSARGS;
#else
    dVAR; dXSBOOTARGSXSAPIVERCHK;
#endif
#if PERL_VERSION_LE(5, 8, 999) /* PERL_VERSION_LT is 5.33+ */
    char* file = __FILE__;
#else
    const char* file = __FILE__;
#endif

    PERL_UNUSED_VAR(file);

    PERL_UNUSED_VAR(cv); /* -W */
    PERL_UNUSED_VAR(items); /* -W */
#if PERL_VERSION_LE(5, 21, 5)
    XS_VERSION_BOOTCHECK;
#  ifdef XS_APIVERSION_BOOTCHECK
    XS_APIVERSION_BOOTCHECK;
#  endif
#endif

        (void)newXSproto_portable("GCC::Builtins::bswap16", XS_GCC__Builtins_bswap16, file, "$");
        (void)newXSproto_portable("GCC::Builtins::bswap32", XS_GCC__Builtins_bswap32, file, "$");
        (void)newXSproto_portable("GCC::Builtins::bswap64", XS_GCC__Builtins_bswap64, file, "$");
        (void)newXSproto_portable("GCC::Builtins::clrsb", XS_GCC__Builtins_clrsb, file, "$");
        (void)newXSproto_portable("GCC::Builtins::clrsbl", XS_GCC__Builtins_clrsbl, file, "$");
        (void)newXSproto_portable("GCC::Builtins::clrsbll", XS_GCC__Builtins_clrsbll, file, "$");
        (void)newXSproto_portable("GCC::Builtins::clz", XS_GCC__Builtins_clz, file, "$");
        (void)newXSproto_portable("GCC::Builtins::clzl", XS_GCC__Builtins_clzl, file, "$");
        (void)newXSproto_portable("GCC::Builtins::clzll", XS_GCC__Builtins_clzll, file, "$");
        (void)newXSproto_portable("GCC::Builtins::ctz", XS_GCC__Builtins_ctz, file, "$");
        (void)newXSproto_portable("GCC::Builtins::ctzl", XS_GCC__Builtins_ctzl, file, "$");
        (void)newXSproto_portable("GCC::Builtins::ctzll", XS_GCC__Builtins_ctzll, file, "$");
        (void)newXSproto_portable("GCC::Builtins::ffs", XS_GCC__Builtins_ffs, file, "$");
        (void)newXSproto_portable("GCC::Builtins::ffsl", XS_GCC__Builtins_ffsl, file, "$");
        (void)newXSproto_portable("GCC::Builtins::ffsll", XS_GCC__Builtins_ffsll, file, "$");
        (void)newXSproto_portable("GCC::Builtins::huge_val", XS_GCC__Builtins_huge_val, file, "");
        (void)newXSproto_portable("GCC::Builtins::huge_valf", XS_GCC__Builtins_huge_valf, file, "");
        (void)newXSproto_portable("GCC::Builtins::huge_vall", XS_GCC__Builtins_huge_vall, file, "");
        (void)newXSproto_portable("GCC::Builtins::inf", XS_GCC__Builtins_inf, file, "");
        (void)newXSproto_portable("GCC::Builtins::infd128", XS_GCC__Builtins_infd128, file, "");
        (void)newXSproto_portable("GCC::Builtins::infd32", XS_GCC__Builtins_infd32, file, "");
        (void)newXSproto_portable("GCC::Builtins::infd64", XS_GCC__Builtins_infd64, file, "");
        (void)newXSproto_portable("GCC::Builtins::inff", XS_GCC__Builtins_inff, file, "");
        (void)newXSproto_portable("GCC::Builtins::infl", XS_GCC__Builtins_infl, file, "");
        (void)newXSproto_portable("GCC::Builtins::nan", XS_GCC__Builtins_nan, file, "$");
        (void)newXSproto_portable("GCC::Builtins::nanf", XS_GCC__Builtins_nanf, file, "$");
        (void)newXSproto_portable("GCC::Builtins::nanl", XS_GCC__Builtins_nanl, file, "$");
        (void)newXSproto_portable("GCC::Builtins::parity", XS_GCC__Builtins_parity, file, "$");
        (void)newXSproto_portable("GCC::Builtins::parityl", XS_GCC__Builtins_parityl, file, "$");
        (void)newXSproto_portable("GCC::Builtins::parityll", XS_GCC__Builtins_parityll, file, "$");
        (void)newXSproto_portable("GCC::Builtins::popcount", XS_GCC__Builtins_popcount, file, "$");
        (void)newXSproto_portable("GCC::Builtins::popcountl", XS_GCC__Builtins_popcountl, file, "$");
        (void)newXSproto_portable("GCC::Builtins::popcountll", XS_GCC__Builtins_popcountll, file, "$");
        (void)newXSproto_portable("GCC::Builtins::powi", XS_GCC__Builtins_powi, file, "$$");
        (void)newXSproto_portable("GCC::Builtins::powif", XS_GCC__Builtins_powif, file, "$$");
        (void)newXSproto_portable("GCC::Builtins::powil", XS_GCC__Builtins_powil, file, "$$");
#if PERL_VERSION_LE(5, 21, 5)
#  if PERL_VERSION_GE(5, 9, 0)
    if (PL_unitcheckav)
        call_list(PL_scopestack_ix, PL_unitcheckav);
#  endif
    XSRETURN_YES;
#else
    Perl_xs_boot_epilog(aTHX_ ax);
#endif
}

#ifdef __cplusplus
}
#endif
